FROM python:3.8-slim

# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load
# the DagsterInstance
RUN pip install -U pip setuptools
RUN pip install --no-cache-dir --default-timeout=100\
    pandas==1.3.3 \
    dagster==0.14.15  \
    dagster-graphql==0.14.15   \
    dagit==0.14.15   \
    dagster-postgres==0.14.15   \
    dagster-docker==0.14.15   \
    dagster-gcp==0.14.15  \
    dagstermill==0.14.15 \
    gcsfs==2022.3.0 \
    dateparser==1.0.0 \
    db-dtypes \
    python-decouple==3.5 \
    mplfinance==0.12.8b9 \
    openpyxl==3.0.9 \
    finnhub-python==2.4.13 \
    markupsafe==2.0.1 \
    jupyter


#WORKDIR /var
#COPY triple-acre-339816-b21b15e6149e.json ./
#ENV GOOGLE_APPLICATION_CREDENTIALS=/var/triple-acre-339816-b21b15e6149e.json

WORKDIR /opt/dagster/app/
# Add repository code
RUN mkdir finapp

COPY finapp/ finapp/

COPY config/local_docker/dagster.yaml config/local_docker/workspace.yaml setup.py ./

RUN pip install -e .

ENV DAGSTER_HOME=/opt/dagster/app/

# Run dagster gRPC server on port 4000

EXPOSE 4000

# Using CMD rather than ENTRYPOINT allows the command to be overridden in
# run launchers or executors to run other commands using this image
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "finapp/repository.py"]