run_launcher:
  module: dagster.core.launcher
  class: DefaultRunLauncher

run_coordinator:
  module: dagster.core.run_coordinator
  class: DefaultRunCoordinator

compute_logs:
  module: dagster.core.storage.local_compute_log_manager
  class: LocalComputeLogManager
  config:
    base_dir: /Users/christianpiconcalderon/PycharmProjects/FinApp/config/local

# example local_artifact_storage setup pointing to /var/shared/dagster directory
local_artifact_storage:
  module: dagster.core.storage.root
  class: LocalArtifactStorage
  config:
    base_dir: /Users/christianpiconcalderon/PycharmProjects/FinApp/config/local

# Configures how long Dagster waits for repositories
# to load before timing out.
code_servers:
  local_startup_timeout: 120