# Workspaces specify where to find user code in order to load it for Dagit and the Dagster CLI.
# See our documentation overview on Workspaces: https://docs.dagster.io/overview/repositories-workspaces/workspaces
load_from:
  - python_package: finapp.finapp
#load_from:
#     - python_file:
#            relative_path: project_dataML/project_dataML.py
#            working_directory: /Users/christianpiconcalderon/PycharmProjects/Data_application_template
