FROM python:3.8-slim

ARG DAGSTER_PG_USERNAME=$DAGSTER_PG_USERNAME
ARG DAGSTER_PG_PASSWORD=$DAGSTER_PG_PASSWORD
ARG DAGSTER_PG_HOST=$DAGSTER_PG_HOST
ARG DAGSTER_PG_DB=$DAGSTER_PG_DB
ARG FINNUB_KEY=$FINNUB_KEY

ENV DAGSTER_HOME=/opt/dagster/app/
ENV GOOGLE_APPLICATION_CREDENTIALS=/var/keyfile.json
# Checkout and install dagster libraries needed to run the gRPC server
# exposing your repository to dagit and dagster-daemon, and to load
# the DagsterInstance
RUN pip install -U pip setuptools

RUN pip install --no-cache-dir --default-timeout=100\
    dagster==0.14.15  \
    dagster-graphql==0.14.15   \
    dagit==0.14.15   \
    dagster-postgres==0.14.15   \
    dagster-docker==0.14.15   \
    dagster-gcp==0.14.15  \
    dagster-pandera==0.14.15 \
    dagstermill==0.14.15 \
    gcsfs \
    dateparser \
    db-dtypes \
    python-decouple \
    mplfinance==0.12.8b9 \
    openpyxl==3.0.9 \
    finnhub-python==2.4.13 \
    markupsafe==2.0.1 \
    pandera \
    pandas==1.3.3 \
    jupyter

WORKDIR $DAGSTER_HOME
# Add repository code
RUN mkdir finapp

COPY ./finapp finapp/

# Run dagster gRPC server on port 4000
EXPOSE 4000

# Using CMD rather than ENTRYPOINT allows the command to be overridden in
# run launchers or executors to run other commands using this image
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "finapp/repository.py"]